// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.src.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250415020229_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Domain.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sin género",
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Real Time Strategy",
                            Name = "RTS"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Racing"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sin plataforma",
                            Name = "None"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Personal Computer",
                            Name = "PC"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Play Station 1",
                            Name = "PS1"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Play Station 2",
                            Name = "PS2"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Nintendo Entertainment System",
                            Name = "NES"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Super Nintendo Entertainment System",
                            Name = "SNES"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
